### ISSUE TITLE
Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by kamrancr7** [aubykhan/flutter_pk#8] opened 2019-03-19 17:09 UTC
After login successfully i got the following exception:

E/flutter (16918): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: No element
E/flutter (16918): #0      List.first (dart:core/runtime/libgrowable_array.dart:216:5)
E/flutter (16918): #1      CustomAppBarState.initState.<anonymous closure>.<anonymous closure> (package:flutter_pk/widgets/custom_app_bar.dart:30:29)

snapshot.hasData on schedule_page.dart file returns true i don't know why
 if (!snapshot.hasData)
          return Center(
            child: Text(
              'Nothing found!',
              style: Theme.of(context).textTheme.title.copyWith(
                    color: Colors.black26,
                    fontWeight: FontWeight.bold,
                  ),
            ),
          );

**Comment by asadullah-yousuf-10p** [comment] 2019-03-21 10:42
You have to have relevant data in Firestore. I have just created #9 to address the same.

**Comment by aubykhan** [comment] 2019-03-21 10:43
You have to have relevant data in Firestore. #9 is created to address the same.

**Comment by kamrancr7** [comment] 2019-03-21 16:57
but when there is no data/collection in firestore then why hasData function returns true??
i add an extra check in if statement and it is working fine 
if (!snapshot.hasData || snapshot.data.documents.length <= 0)
but i don't know it is correct or not

**Comment by aubykhan** [comment] 2019-03-22 05:23
The issue is originated inside CustomAppBar and the reason is the same it i.e. it can't find the data on your Firestore instance. I'll go ahead and add a Firestore data setup section in README along with data files as per #9. You'll have to import them in your own Firestore instance in order to run this app.

**Comment by aubykhan** [comment] 2019-03-22 05:58
I've just pushed [a change](https://github.com/aubykhan/flutter_pk/commit/01b278ec72b2b802f4f48189e9a25aa4c57f2397) which will help you setup your Firestore data. See [this](https://github.com/aubykhan/flutter_pk#firebase) section.

I'm closing out this issue now.

**Closed by aubykhan** 2019-03-22 05:58 UTC
Labels: bug

**Comment by kamrancr7** [comment] 2019-03-22 18:34
now it's working perfectly.
